name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint backend with flake8
        run: |
          pip install flake8
          # Fail the build if there are any lint errors
          flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 backend --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run backend tests
        run: pytest backend/tests

      # Frontend build step (optional)
      - name: Build frontend
        run: |
          echo "Skipping frontend build; static assets are served directly."

      # Docker build step (optional)
      - name: Build Docker image
        run: |
          docker build -t skincare-agent-app:latest .
      # The image can be pushed to a registry by adding login and push steps.
